language: cpp
compiler:
  - clang
before_install:
  - lsb_release -a
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - apt-cache search clang
  - apt-cache search 'g\+\+'
  - sudo apt-get install -qq clang-3.5 fglrx gfortran g++-4.8 opencl-headers
  - g++ --version
  - clang++ --version
  - whereis clang
  - whereis clang++
  - ls -l /usr/local/clang-3.5/bin/clang++
  - whereis gcc
  - whereis g++
  - ls -l /usr/bin/g++-4.8
  - ls -l /usr/include/c++/4.8
# - sudo update-alternatives --set cc /usr/bin/clang-3.5
# - sudo update-alternatives --set c++ /usr/bin/clang-3.5
script:
# - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
# - make -j8
