language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq subversion
  - svn co -q http://llvm.org/svn/llvm-project/libcxx/tags/RELEASE_34/final/ libcxx
  - svn co -q http://llvm.org/svn/llvm-project/libcxxabi/tags/RELEASE_30/final/ libcxxabi
  - mkdir -p build_libcxx
  - cd build_libcxx
  - cmake -DLIBCXXABI_LIBCXX_INCLUDE_PATHS=../libcxx/include -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../libcxxabi
  - cmake -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXX_LIBCXXABI_INCLUDE_PATHS=../libcxxabi/include -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../libcxx
  - make -j8
  - sudo make install
  - cd ..
  - sudo apt-get install -qq fglrx gfortran opencl-headers
script:
  - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  - make -j8
