language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx && ls /usr/include/c++; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
  - if [ "$CXX" == "clang++" ]; then ls /usr/include/c++; fi
  - sudo apt-get install -qq cmake fglrx gfortran-4.8 opencl-headers
script:
  - $CXX --version
  # - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  # - find . -name CMakeOutput.log
  # - cat CMakeFiles/CMakeOutput.log
  # - make -j8
