language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx gfortran opencl-headers
script:
  - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  - make -j8
