language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi
  - sudo apt-get install -qq cmake fglrx gfortran-4.8 opencl-headers
script:
  - $CXX --version
  # - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  # - find . -name CMakeOutput.log
  # - cat CMakeFiles/CMakeOutput.log
  # - make -j8
