language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-add-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake fglrx gfortran opencl-headers
  - ls /usr/include/
  - ls /usr/include/c++/4.6/
script:
  - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  - make -j8
