language: cpp
compiler:
  - clang
before_install:
  - lsb_release -a
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - apt-cache search clang
  - apt-cache search 'g\+\+'
  - sudo apt-get install -qq clang-3.5 fglrx gfortran g++-4.8 opencl-headers
  - g++ --version
  - clang++ --version
script:
  - cmake -DBUILD_CLIENT=OFF -DBUILD_KTEST=OFF -DBUILD_TEST=OFF .
  - make -j8
